# A generic, single database configuration.

[alembic]
# path to migration script
script_location = alembic

# template used to generate migration file names; The default is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as well as the filename.
# string value such as 'UTC', 'US/Eastern', or 'Europe/London'.
# timezone =

# max length of characters in the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be treated as revisions
# sourceless = false

# version location specification; This defaults
# to alembic/versions. Operating system path separators are used.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# set to 'true' to search source_paths recursively for
# python files containing alembic revisions
# recursive_version_locations = false

# set to 'true' to allow alembic to downgrade to base
# downgrade_to_base = false

# output_encoding = utf-8

sqlalchemy.url = postgresql+psycopg://savora:savora@localhost:5432/savora


[post_write_hooks]
# post_write_hooks defines scripts or python functions that are run
# on newly-generated revision scripts.  See documentation for further
# detail and examples

# format using "black" - use the console_scripts runner, outputting to "black"
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
